import { useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ChevronRight, Plus, ShieldCheck } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { submitTransfer, type KycCredential } from '@/lib/api';
import { authenticate, canUseBiometrics } from '@/lib/auth';
import { debit, formatMinor, getBalanceMinor } from '@/lib/balance';
import { syncBackup } from '@/lib/cloud-backup';
import { hasPin } from '@/lib/pin';
import { isProverAvailable, prove } from '@/lib/prover';
import { useBalance, useRecipients, QK } from '@/lib/queries';
import { initials, type Recipient } from '@/lib/recipients';
import { getSecret, SecureKey } from '@/lib/secure-store';
import { secureRandomU64 } from '@/lib/wallet';
import { Button, Card, Screen } from '@/components/ui';
import { PinPromptModal } from '@/components/pin-prompt';
import { useToast } from '@/components/toast';
import { env } from '@/config/env';
import { Palette, Radius, Spacing, Typography } from '@/constants/theme';

type Phase = 'idle' | 'proving' | 'submitting' | 'sent' | 'error';

/**
 * Send flow: choose a recipient → enter an amount → prove on-device → relay. The Groth16 proof is
 * generated by the native Rust prover off the JS thread (honest progress bar). The amount and secret
 * never leave the phone; only a commitment goes on-chain, and the local balance is debited.
 */
export default function SendScreen() {
  const router = useRouter();
  const toast = useToast();
  const queryClient = useQueryClient();
  const { recipientId } = useLocalSearchParams<{ recipientId?: string }>();
  const { data: recipients } = useRecipients();
  const { data: balanceMinor } = useBalance();

  const [picked, setPicked] = useState<Recipient | null>(null);
  const [amount, setAmount] = useState('');
  const [secret, setSecret] = useState<string | null>(null);
  const [credential, setCredential] = useState<KycCredential | null>(null);
  const [phase, setPhase] = useState<Phase>('idle');
  const [showPinPrompt, setShowPinPrompt] = useState(false);
  const [progress, setProgress] = useState(0);
  const [message, setMessage] = useState('');
  const [txHash, setTxHash] = useState('');
  const [error, setError] = useState('');
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  // A recipient passed via route params is fixed; otherwise the user picks one below.
  const selected = useMemo<Recipient | null>(() => {
    if (recipientId) return recipients?.find((r) => r.id === recipientId) ?? null;
    return picked;
  }, [recipientId, recipients, picked]);

  useEffect(() => {
    let active = true;
    (async () => {
      const s = await getSecret(SecureKey.zkSecretKey);
      const c = await getSecret(SecureKey.kycCredential);
      if (!active) return;
      setSecret(s);
      if (c) {
        try {
          setCredential(JSON.parse(c) as KycCredential);
        } catch {
          /* ignore malformed */
        }
      }
    })();
    return () => {
      active = false;
      if (timer.current) clearInterval(timer.current);
    };
  }, []);

  const startProgress = () => {
    setProgress(0.05);
    timer.current = setInterval(() => setProgress((p) => (p < 0.9 ? p + 0.03 : p)), 250);
  };
  const stopProgress = () => {
    if (timer.current) {
      clearInterval(timer.current);
      timer.current = null;
    }
  };

  const amt = Number(amount);
  const amountValid = Number.isInteger(amt) && amt >= 1 && amt <= 9999;
  const canAfford = amountValid && amt * 100 <= (balanceMinor ?? 0);

  // The actual prove + relay, run only after the user has authorized the payment (step-up).
  const runTransfer = useCallback(async () => {
    if (!secret || !credential) return;
    try {
      setPhase('proving');
      setMessage('Securing your transfer…');
      startProgress();

      const now = Math.floor(Date.now() / 1000);
      const transferId = secureRandomU64();
      const blob = await prove({
        amount: String(amt),
        secret,
        transferId,
        kycLevel: String(credential.kycLevel),
        expiry: String(credential.expiry),
        currentTime: String(now),
        sigRx: credential.signature.rX,
        sigRy: credential.signature.rY,
        sigS: credential.signature.s,
        anchorPkX: credential.anchor.x,
        anchorPkY: credential.anchor.y,
      });

      stopProgress();
      setProgress(1);
      setPhase('submitting');
      setMessage('Submitting to Stellar…');
      const resp = await submitTransfer(blob);
      if (resp.status === 'confirmed') {
        setTxHash(resp.txHash ?? '');
        await debit(amt);
        await queryClient.invalidateQueries({ queryKey: QK.balance });
        await queryClient.invalidateQueries({ queryKey: QK.history });
        setPhase('sent');
        toast.success('Sent — no amount on-chain');
        void syncBackup(); // keep the cloud backup's balance snapshot fresh (silent, best-effort)
      } else {
        setError(`Transfer ${resp.status}.`);
        setPhase('error');
        toast.error(`Transfer ${resp.status}`);
      }
    } catch (e) {
      stopProgress();
      const msg = e instanceof Error ? e.message : 'send failed';
      setError(msg);
      setPhase('error');
      toast.error(msg);
    }
  }, [amt, secret, credential, queryClient, toast]);

  // Validate, then require a step-up (biometric, or PIN as fallback) before spending.
  const onSend = useCallback(async () => {
    setError('');
    if (!amountValid) {
      setError('Amount must be a whole number between 1 and 9999.');
      return;
    }
    if (!secret || !credential) {
      setError('Verify your identity first.');
      return;
    }
    // Re-read balance at send time (source of truth) to avoid a stale cached value.
    if (amt * 100 > (await getBalanceMinor())) {
      setError('Insufficient balance — add money first.');
      return;
    }

    // Payment step-up: biometric if available, otherwise the PIN; if neither is set up, proceed.
    if (await canUseBiometrics()) {
      const ok = await authenticate('Approve this transfer');
      if (!ok) {
        setError('Authentication required to send.');
        return;
      }
      await runTransfer();
    } else if (await hasPin()) {
      setShowPinPrompt(true);
    } else {
      await runTransfer();
    }
  }, [amountValid, amt, secret, credential, runTransfer]);

  const busy = phase === 'proving' || phase === 'submitting';
  const list = useMemo(() => recipients ?? [], [recipients]);

  // ---- Success state ----
  if (phase === 'sent') {
    return (
      <Screen scroll>
        <View style={styles.successWrap}>
          <View style={styles.successBadge}>
            <ShieldCheck color={Palette.accent} size={44} strokeWidth={1.8} />
          </View>
          <Text style={styles.successTitle}>Sent privately ✅</Text>
          <Text style={styles.successBody}>
            {formatMinor(amt * 100)} to {selected?.name ?? 'your recipient'}
          </Text>
          {txHash ? <Text style={styles.mono}>tx {txHash.slice(0, 16)}…</Text> : null}
          <Text style={styles.enclave}>No amount is visible on-chain — only the commitment.</Text>
          <Button label="Done" onPress={() => router.back()} style={styles.doneBtn} />
        </View>
      </Screen>
    );
  }

  // ---- Missing KYC ----
  if (!credential) {
    return (
      <Screen scroll>
        <Card style={styles.gateCard}>
          <ShieldCheck color={Palette.accent} size={22} strokeWidth={2} />
          <Text style={styles.gateTitle}>Verify your identity first</Text>
          <Text style={styles.gateBody}>
            One quick check with the anchor unlocks private transfers.
          </Text>
          <Button label="Verify identity" onPress={() => router.replace('/kyc')} />
        </Card>
      </Screen>
    );
  }

  // ---- Choose recipient ----
  if (!selected) {
    return (
      <Screen scroll>
        <Text style={styles.subtitle}>Who are you sending to?</Text>
        {list.length === 0 ? (
          <Card style={styles.gateCard}>
            <Text style={styles.gateBody}>No recipients yet. Add someone to send money to.</Text>
          </Card>
        ) : (
          <View style={styles.pickList}>
            {list.map((r) => (
              <Pressable key={r.id} onPress={() => setPicked(r)}>
                <Card style={styles.pickRow}>
                  <View style={styles.avatar}>
                    <Text style={styles.avatarText}>{initials(r.name)}</Text>
                  </View>
                  <View style={styles.flex}>
                    <Text style={styles.name}>{r.name}</Text>
                    <Text style={styles.handle} numberOfLines={1}>
                      {r.handle} · {r.country}
                    </Text>
                  </View>
                  <ChevronRight color={Palette.textMuted} size={20} />
                </Card>
              </Pressable>
            ))}
          </View>
        )}
        <Button
          label="Add recipient"
          variant="secondary"
          icon={<Plus color={Palette.white} size={18} strokeWidth={2} />}
          onPress={() => router.push('/recipient-new')}
          style={styles.add}
        />
      </Screen>
    );
  }

  // ---- Amount + confirm ----
  return (
    <Screen scroll>
      {/* Selected recipient */}
      <Card style={styles.recipientCard}>
        <View style={styles.avatar}>
          <Text style={styles.avatarText}>{initials(selected.name)}</Text>
        </View>
        <View style={styles.flex}>
          <Text style={styles.name}>{selected.name}</Text>
          <Text style={styles.handle} numberOfLines={1}>
            {selected.handle} · {selected.country}
          </Text>
        </View>
        {!recipientId ? (
          <Pressable hitSlop={8} onPress={() => setPicked(null)} disabled={busy}>
            <Text style={styles.change}>Change</Text>
          </Pressable>
        ) : null}
      </Card>

      {/* Amount */}
      <View style={styles.amountWrap}>
        <Text style={styles.amountLabel}>Amount ({env.currency})</Text>
        <View style={styles.amountRow}>
          <Text style={styles.currency}>{env.currency}</Text>
          <TextInput
            style={styles.amountInput}
            value={amount}
            onChangeText={setAmount}
            keyboardType="number-pad"
            placeholder="0"
            placeholderTextColor={Palette.textMuted}
            editable={!busy}
            autoFocus
          />
        </View>
        <Text style={styles.balanceHint}>
          Available: {formatMinor(balanceMinor ?? 0)}
          {amountValid && !canAfford ? '  ·  Insufficient balance' : ''}
        </Text>
      </View>

      <Button
        label={busy ? message : 'Send privately'}
        onPress={onSend}
        disabled={busy || !amountValid || !canAfford}
      />

      {busy ? (
        <View style={styles.progressWrap}>
          <View style={styles.progressTrack}>
            <View style={[styles.progressFill, { width: `${Math.round(progress * 100)}%` }]} />
          </View>
          <View style={styles.progressRow}>
            <ActivityIndicator color={Palette.accent} />
            <Text style={styles.progressText}>{message}</Text>
          </View>
        </View>
      ) : null}

      {error ? <Text style={styles.error}>{error}</Text> : null}
      <Text style={styles.enclave}>
        The amount is proved compliant on this device and never leaves it — only a commitment goes
        on-chain.
      </Text>
      {!isProverAvailable ? (
        <Text style={styles.hint}>
          On-device prover not built into this app yet. Rebuild with `npx expo run:android` to
          enable proving.
        </Text>
      ) : null}

      <PinPromptModal
        visible={showPinPrompt}
        title="Approve this transfer"
        subtitle="Enter your PIN to send."
        onSuccess={() => {
          setShowPinPrompt(false);
          runTransfer();
        }}
        onCancel={() => setShowPinPrompt(false)}
      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  subtitle: { ...Typography.body, color: Palette.textSecondary, marginBottom: Spacing.four },
  flex: { flex: 1 },
  gateCard: { gap: Spacing.three, alignItems: 'flex-start', marginBottom: Spacing.four },
  gateTitle: { ...Typography.section, color: Palette.white },
  gateBody: { ...Typography.caption, color: Palette.textSecondary },
  pickList: { gap: Spacing.three, marginBottom: Spacing.four },
  pickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
  },
  recipientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
    marginBottom: Spacing.six,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: Radius.full,
    backgroundColor: Palette.bgSelected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { ...Typography.section, color: Palette.white },
  name: { ...Typography.body, color: Palette.white },
  handle: { ...Typography.micro, color: Palette.textSecondary },
  change: { ...Typography.caption, color: Palette.accent, fontWeight: '600' },
  add: { marginTop: Spacing.two },
  amountWrap: { marginBottom: Spacing.six, gap: Spacing.two },
  amountLabel: { ...Typography.caption, color: Palette.textSecondary },
  amountRow: { flexDirection: 'row', alignItems: 'baseline', gap: Spacing.two },
  currency: { ...Typography.title, color: Palette.textSecondary },
  amountInput: {
    ...Typography.displayBalance,
    color: Palette.white,
    flex: 1,
    padding: 0,
  },
  balanceHint: { ...Typography.micro, color: Palette.textMuted },
  progressWrap: { marginTop: Spacing.five, gap: Spacing.three },
  progressTrack: {
    height: 6,
    borderRadius: Radius.pill,
    backgroundColor: Palette.bgElevated,
    overflow: 'hidden',
  },
  progressFill: { height: 6, borderRadius: Radius.pill, backgroundColor: Palette.accent },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three },
  progressText: { ...Typography.caption, color: Palette.textSecondary },
  error: { ...Typography.caption, color: '#ff6b6b', marginTop: Spacing.four },
  enclave: { ...Typography.micro, color: Palette.textMuted, marginTop: Spacing.four },
  hint: { ...Typography.micro, color: Palette.textMuted, marginTop: Spacing.two },
  successWrap: { alignItems: 'center', gap: Spacing.three, paddingTop: Spacing.seven },
  successBadge: {
    width: 88,
    height: 88,
    borderRadius: Radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.glass,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.glassBorder,
    marginBottom: Spacing.two,
  },
  successTitle: { ...Typography.title, color: Palette.white },
  successBody: { ...Typography.section, color: Palette.accent },
  mono: { ...Typography.micro, color: Palette.textMuted },
  doneBtn: { marginTop: Spacing.six, alignSelf: 'stretch' },
});
