import { useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ChevronRight, Plus, ShieldCheck } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { ApiError, submitTransfer, type KycCredential } from '@/lib/api';
import { authenticate, canUseBiometrics } from '@/lib/auth';
import { debit, formatBalance, getBalanceMinor, settlementDenomination } from '@/lib/balance';
import { syncBackup } from '@/lib/cloud-backup';
import { useMoney, usesPool } from '@/hooks/use-money';
import { getStoredCredential, isExpired } from '@/lib/kyc';
import { formatAmount, minorPerUnit, parseAmountToMinor, tierLimit } from '@prova/shared';
import { hasPin } from '@/lib/pin';
import { InsufficientFunds, sendPrivately, type Payee } from '@/lib/pool';
import { isProverAvailable, prove } from '@/lib/prover';
import { useRecipients, QK } from '@/lib/queries';
import { initials, type Recipient } from '@/lib/recipients';
import { getSecret, SecureKey } from '@/lib/secure-store';
import { secureRandomU64 } from '@/lib/wallet';
import { ConfirmSendSheet } from '@/components/confirm-send';
import { ConnectionGate } from '@/components/connection-gate';
import { Loader } from '@/components/loader';
import { PaymentResult } from '@/components/payment-result';
import { Button, Card, Screen } from '@/components/ui';
import { PinPromptModal } from '@/components/pin-prompt';
import { Palette, Radius, Spacing, Typography } from '@/constants/theme';

type Phase = 'idle' | 'proving' | 'submitting' | 'sent' | 'processing' | 'error';

/**
 * Send flow: choose a recipient → enter an amount → prove on-device → relay. The Groth16 proof is
 * generated by the native Rust prover off the JS thread (honest progress bar). The amount and secret
 * never leave the phone; only a commitment goes on-chain, and the local balance is debited.
 */
export default function SendScreen() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { recipientId } = useLocalSearchParams<{ recipientId?: string }>();
  const { data: recipients } = useRecipients();
  const money = useMoney();

  const [picked, setPicked] = useState<Recipient | null>(null);
  const [amount, setAmount] = useState('');
  const [secret, setSecret] = useState<string | null>(null);
  const [credential, setCredential] = useState<KycCredential | null>(null);
  const [phase, setPhase] = useState<Phase>('idle');
  const [showPinPrompt, setShowPinPrompt] = useState(false);
  /** Review step: what is being sent, and to whom, before anything is authorised. */
  const [confirming, setConfirming] = useState(false);
  const [progress, setProgress] = useState(0);
  const [message, setMessage] = useState('');
  const [txHash, setTxHash] = useState('');
  const [error, setError] = useState('');
  /** Machine-readable decline/processing reason driving the result screen's explanation. */
  const [reason, setReason] = useState('');
  /**
   * What actually went wrong, in the server's own words, for failures with no specific copy.
   *
   * Kept because the alternative is telling someone "something went wrong" about their money and
   * leaving them — and whoever they ask for help — with nothing to go on.
   */
  const [detail, setDetail] = useState('');
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  // A recipient passed via route params is fixed; otherwise the user picks one below.
  const selected = useMemo<Recipient | null>(() => {
    if (recipientId) return recipients?.find((r) => r.id === recipientId) ?? null;
    return picked;
  }, [recipientId, recipients, picked]);

  useEffect(() => {
    let active = true;
    (async () => {
      const s = await getSecret(SecureKey.zkSecretKey);
      // Only accept a credential the circuit would still honour: an expired one produces a proof
      // the contract rejects, so treat it as "not verified" and send the user back to KYC.
      const stored = await getStoredCredential();
      if (!active) return;
      setSecret(s);
      setCredential(stored && !isExpired(stored) ? stored : null);
    })();
    return () => {
      active = false;
      if (timer.current) clearInterval(timer.current);
    };
  }, []);

  const startProgress = () => {
    setProgress(0.05);
    timer.current = setInterval(() => setProgress((p) => (p < 0.9 ? p + 0.03 : p)), 250);
  };
  // Same progress bar, but the copy escalates with elapsed time. Measured on-device this proof runs
  // ~2.6s (see Docs/shielded-pool.md §10.8) — comfortably under the 5s "just show a spinner" line —
  // but phones vary a lot more than one test unit, so this is a cheap safety net: if a slower device
  // ever takes noticeably longer, the copy adapts instead of just sitting there looking frozen.
  const startPoolProgress = () => {
    setProgress(0.05);
    const startedAt = Date.now();
    timer.current = setInterval(() => {
      setProgress((p) => (p < 0.9 ? p + 0.03 : p));
      const elapsed = Date.now() - startedAt;
      setMessage(
        elapsed < 5_000
          ? 'Securing your transfer…'
          : elapsed < 20_000
            ? 'Still securing your transfer — this can take longer on some phones…'
            : 'Almost there — thanks for waiting…',
      );
    }, 250);
  };
  const stopProgress = () => {
    if (timer.current) {
      clearInterval(timer.current);
      timer.current = null;
    }
  };

  // Spending denomination: what the balance is actually held in, falling back to what this build
  // settles in for an account that has not been funded yet (nothing is affordable then anyway).
  const spendDenom = money.denom ?? settlementDenomination();

  // Parsed from the typed string, never `Number(text) * 100`: floating point turns 10.07 into
  // 1006.9999999999999, which is a different amount of money than the person asked to send.
  const parsedMinor = parseAmountToMinor(amount, spendDenom);
  const amtMinor = parsedMinor ?? 0;
  const amt = amtMinor / minorPerUnit(spendDenom);
  const withinTier = amt <= tierLimit(credential?.kycLevel ?? 0);
  const amountValid = parsedMinor !== null && parsedMinor > 0 && withinTier;

  const canAfford = amountValid && amtMinor <= money.spendable;
  /**
   * The circuit spends exactly one note, so the ceiling on a single transfer is the largest note —
   * not the total. Checked here, before anything is proved, because the alternative is a rejection
   * after the user has entered an amount and authenticated.
   */
  const fitsOneNote = amtMinor <= money.largestNote;
  const splitNeeded = canAfford && !fitsOneNote;

  /**
   * Pool-mode send: the real shielded pool, wired to `sendPrivately()`. The balance comes from the
   * chain (via `useMoney()`), so — unlike the legacy path below — there is no local `debit()` call to
   * make; double-crediting would invent money that does not exist.
   */
  const runPoolTransfer = useCallback(async () => {
    if (!selected?.poolOwnerPk || !selected.poolEncPkX || !selected.poolEncPkY) {
      setError(
        'Add this recipient’s pool address first — ask them for it from Account → Receive privately.',
      );
      return;
    }
    const payee: Payee = {
      ownerPk: selected.poolOwnerPk,
      encPkX: selected.poolEncPkX,
      encPkY: selected.poolEncPkY,
    };
    try {
      setPhase('proving');
      setMessage('Securing your transfer…');
      startPoolProgress();

      const hash = await sendPrivately(
        // Minor units throughout: the pool layer speaks the same units every screen displays, so
        // there is no whole-unit conversion left to get wrong.
        amtMinor,
        payee,
        (stage) => {
          if (stage === 'submitting') {
            stopProgress();
            setProgress(1);
            setPhase('submitting');
            setMessage('Submitting to Stellar…');
          }
        },
        // Local history only — the recipient's name stays on this phone and is never transmitted.
        selected.name,
      );

      setTxHash(hash);
      await queryClient.invalidateQueries({ queryKey: QK.poolBalance });
      await queryClient.invalidateQueries({ queryKey: QK.activity });
      setPhase('sent');
      void syncBackup(); // keep the cloud backup's balance snapshot fresh (silent, best-effort)
    } catch (e) {
      stopProgress();
      if (e instanceof InsufficientFunds) {
        // Not a proving/network failure — a precondition that failed before anything was submitted.
        // Send the user back to the amount screen with a specific, actionable message rather than a
        // full-page "transfer failed", which would be misleading (nothing was ever attempted).
        setError(
          e.largestNoteMinor > 0
            ? `Your balance is split across notes. The most you can send in one transfer is ` +
                `${formatBalance(e.largestNoteMinor, money.denom)}.`
            : 'Not enough spendable balance.',
        );
        setPhase('idle');
        return;
      }
      const msg = e instanceof Error ? e.message : 'send failed';
      if (/still confirming|verification|verify/i.test(msg)) {
        setError(msg);
        setPhase('idle');
        return;
      }
      // A network failure after submitting is ambiguous: the transfer may still be in flight.
      // Treat it as "processing" rather than "failed" so nobody is nudged into paying twice.
      /*
       * Did the request reach the server?
       *
       * Only a transport failure or an abort leaves the outcome genuinely unknown — the relay
       * may have submitted and the reply been lost, so the user must NOT be nudged into paying
       * twice. `api` gives those status 0. Anything with a real status is the server having
       * answered: it did not submit, and calling that "processing" strands the user waiting for
       * a payment that will never arrive.
       *
       * Branching on `status`, not on the text. This used to scan the message for "network" and
       * friends, which broke the moment the server's own words were shown: the relay runs the
       * Stellar CLI with `--network testnet`, so its error output contains "network" and every
       * definite failure was relabelled as still-in-flight. ApiError says as much on `code`:
       * branch on this, never on the message.
       */
      const ambiguous = e instanceof ApiError && e.status === 0;
      setReason(ambiguous ? 'timeout' : 'unknown');
      /*
       * Only the server's own sentence is shown to the user.
       *
       * The result screen falls back to `detail` when it has no tailored copy for a reason, which is
       * right when `detail` was written for a person and wrong when it was not. API error messages
       * are written for a person. A thrown `Error` from the prover, the native module or the JS
       * runtime is not — and passing those straight through is how a wall of `[Diagnostic Event]
       * contract:CBLL…, topics:[error, Error(Contract, #4)]` ended up on the screen of someone who
       * only wanted to know where their money went.
       *
       * So: server copy passes, everything else falls back to the generic line. Blank when
       * ambiguous too — that path says the transfer may still land, and an error message under that
       * heading would contradict it.
       */
      const fromServer = e instanceof ApiError && e.status > 0;
      setDetail(!ambiguous && fromServer ? msg : '');
      setPhase(ambiguous ? 'processing' : 'error');

      /*
       * Refresh history on the way out, not only on success.
       *
       * `sendPrivately` writes its activity entry before it relays, and settles it to failed or
       * leaves it processing. Both are new rows. Without this the user taps Done, lands on a home
       * screen that still shows the list from before they pressed send, and has no record at all of
       * the payment they just watched fail — which is exactly the "nothing happened" the result
       * screen is trying not to be.
       */
      await queryClient.invalidateQueries({ queryKey: QK.activity });
      await queryClient.invalidateQueries({ queryKey: QK.poolBalance });
    }
  }, [amtMinor, selected, queryClient, money.denom]);

  // The legacy per-transfer path (circuit v2) — unchanged, still used when this build's money lives
  // in the local counter (`EXPO_PUBLIC_DEPOSIT_MODE=simulated`) rather than the shielded pool.
  const runLegacyTransfer = useCallback(async () => {
    if (!secret || !credential) return;
    try {
      setPhase('proving');
      setMessage('Securing your transfer…');
      startProgress();

      const now = Math.floor(Date.now() / 1000);
      const transferId = secureRandomU64();
      const blob = await prove({
        amount: String(amt),
        secret,
        transferId,
        kycLevel: String(credential.kycLevel),
        expiry: String(credential.expiry),
        currentTime: String(now),
        sigRx: credential.signature.rX,
        sigRy: credential.signature.rY,
        sigS: credential.signature.s,
        anchorPkX: credential.anchor.x,
        anchorPkY: credential.anchor.y,
      });

      stopProgress();
      setProgress(1);
      setPhase('submitting');
      setMessage('Submitting to Stellar…');
      const resp = await submitTransfer(blob);
      setTxHash(resp.txHash ?? '');
      if (resp.status === 'confirmed') {
        await debit(amt);
        await queryClient.invalidateQueries({ queryKey: QK.balance });
        await queryClient.invalidateQueries({ queryKey: QK.history });
        setPhase('sent');
        void syncBackup(); // keep the cloud backup's balance snapshot fresh (silent, best-effort)
      } else if (
        resp.status === 'pending' ||
        resp.status === 'submitting' ||
        resp.status === 'submitted'
      ) {
        // Accepted but not yet confirmed. Money may still land, so we must NOT say it failed —
        // the user is told to wait rather than retry, which would risk a double payment.
        setPhase('processing');
      } else {
        setReason(resp.status === 'rejected' ? 'rejected' : 'unknown');
        // No detail to add: the relay accepted the request and reported a terminal status, so the
        // status IS the explanation. A non-2xx instead throws, and the catch below carries the
        // server's own message — which is the path an outright failure takes.
        setPhase('error');
      }
    } catch (e) {
      stopProgress();
      // A network failure after submitting is ambiguous: the transfer may still be in flight.
      // Treat it as "processing" rather than "failed" so nobody is nudged into paying twice.
      const msg = e instanceof Error ? e.message : 'send failed';
      /*
       * Did the request reach the server?
       *
       * Only a transport failure or an abort leaves the outcome genuinely unknown — the relay
       * may have submitted and the reply been lost, so the user must NOT be nudged into paying
       * twice. `api` gives those status 0. Anything with a real status is the server having
       * answered: it did not submit, and calling that "processing" strands the user waiting for
       * a payment that will never arrive.
       *
       * Branching on `status`, not on the text. This used to scan the message for "network" and
       * friends, which broke the moment the server's own words were shown: the relay runs the
       * Stellar CLI with `--network testnet`, so its error output contains "network" and every
       * definite failure was relabelled as still-in-flight. ApiError says as much on `code`:
       * branch on this, never on the message.
       */
      const ambiguous = e instanceof ApiError && e.status === 0;
      setReason(ambiguous ? 'timeout' : 'unknown');
      /*
       * Only the server's own sentence is shown to the user.
       *
       * The result screen falls back to `detail` when it has no tailored copy for a reason, which is
       * right when `detail` was written for a person and wrong when it was not. API error messages
       * are written for a person. A thrown `Error` from the prover, the native module or the JS
       * runtime is not — and passing those straight through is how a wall of `[Diagnostic Event]
       * contract:CBLL…, topics:[error, Error(Contract, #4)]` ended up on the screen of someone who
       * only wanted to know where their money went.
       *
       * So: server copy passes, everything else falls back to the generic line. Blank when
       * ambiguous too — that path says the transfer may still land, and an error message under that
       * heading would contradict it.
       */
      const fromServer = e instanceof ApiError && e.status > 0;
      setDetail(!ambiguous && fromServer ? msg : '');
      setPhase(ambiguous ? 'processing' : 'error');
    }
  }, [amt, secret, credential, queryClient]);

  const runTransfer = usesPool ? runPoolTransfer : runLegacyTransfer;

  // Validate, then require a step-up (biometric, or PIN as fallback) before spending.
  const onSend = useCallback(async () => {
    setError('');
    if (!amountValid) {
      setError('Amount must be a whole number between 1 and 9999.');
      return;
    }
    if (!secret || !credential) {
      setError('Verify your identity first.');
      return;
    }
    if (usesPool) {
      // The pool's own InsufficientFunds check (thrown from sendPrivately) is the authoritative
      // guard — it also catches the "balance is there but fragmented across notes" case this
      // simpler pre-check cannot express. This is just the fast, cheap rejection.
      if (amtMinor > money.spendable) {
        setReason('insufficient_funds');
        setPhase('error');
        return;
      }
    } else if (amtMinor > (await getBalanceMinor())) {
      // Re-read balance at send time (source of truth) to avoid a stale cached value.
      setReason('insufficient_funds');
      setPhase('error');
      return;
    }
    // Tier limit (see Docs/kyc-verification.md §9 — a product control, enforced here and server-side).
    if (amt > tierLimit(credential.kycLevel)) {
      setReason('limit_exceeded');
      setPhase('error');
      return;
    }

    // Everything checks out — show what is about to happen and let the user confirm it.
    //
    // The step-up that follows is a fingerprint prompt, and the OS dialog can only show a single
    // line of text: it cannot say how much, or to whom. Without this sheet the last thing a person
    // sees before their money leaves is a generic "Approve this transfer".
    setConfirming(true);
  }, [amountValid, amt, amtMinor, secret, credential, money.spendable]);

  /** Confirmed on the review sheet: take the step-up, then spend. */
  const onConfirmed = useCallback(async () => {
    setConfirming(false);
    // Payment step-up: biometric if available, otherwise the PIN; if neither is set up, proceed.
    if (await canUseBiometrics()) {
      const ok = await authenticate('Approve this transfer');
      if (!ok) {
        setError('Authentication required to send.');
        return;
      }
      await runTransfer();
    } else if (await hasPin()) {
      setShowPinPrompt(true);
    } else {
      await runTransfer();
    }
  }, [runTransfer]);

  const busy = phase === 'proving' || phase === 'submitting';
  const list = useMemo(() => recipients ?? [], [recipients]);

  // ---- Terminal outcomes: success / still-processing / failed ----
  if (phase === 'sent' || phase === 'processing' || phase === 'error') {
    const receipt = {
      amount: formatAmount(amtMinor, spendDenom),
      recipientName: selected?.name ?? 'your recipient',
      recipientHandle: selected?.handle,
      reference: txHash || undefined,
      dateTime: new Date().toLocaleString(),
      method: 'Prova private transfer',
      status:
        phase === 'sent' ? 'Completed' : phase === 'processing' ? 'Processing' : 'Not completed',
    };
    return (
      <PaymentResult
        outcome={phase === 'sent' ? 'success' : phase === 'processing' ? 'processing' : 'failed'}
        receipt={receipt}
        reasonCode={reason}
        detail={detail}
        onRetry={() => {
          setReason('');
          setError('');
          setProgress(0);
          setPhase('idle');
        }}
        onDone={() => router.back()}
      />
    );
  }

  // ---- Missing KYC ----
  if (!credential) {
    return (
      <Screen scroll>
        <Card style={styles.gateCard}>
          <ShieldCheck color={Palette.accent} size={22} strokeWidth={2} />
          <Text style={styles.gateTitle}>Verify your identity first</Text>
          <Text style={styles.gateBody}>
            One quick check with the anchor unlocks private transfers.
          </Text>
          <Button label="Verify identity" onPress={() => router.replace('/kyc')} />
        </Card>
      </Screen>
    );
  }

  // ---- Choose recipient ----
  if (!selected) {
    return (
      <Screen scroll>
        <Text style={styles.subtitle}>Who are you sending to?</Text>
        {list.length === 0 ? (
          <Card style={styles.gateCard}>
            <Text style={styles.gateBody}>No recipients yet. Add someone to send money to.</Text>
          </Card>
        ) : (
          <View style={styles.pickList}>
            {list.map((r) => {
              // Recipients saved before the address became mandatory — and any restored from an
              // older backup — have no pool address, so they cannot be paid. Previously they looked
              // identical here and failed only after the amount was entered and the biometric
              // passed, which is the worst moment to learn it.
              const payable = payableRecipient(r);
              return (
                <Pressable
                  key={r.id}
                  onPress={() => payable && setPicked(r)}
                  disabled={!payable}
                  accessibilityState={{ disabled: !payable }}>
                  <Card style={payable ? styles.pickRow : styles.pickRowDisabled}>
                    <View style={styles.avatar}>
                      <Text style={styles.avatarText}>{initials(r.name)}</Text>
                    </View>
                    <View style={styles.flex}>
                      <Text style={styles.name}>{r.name}</Text>
                      <Text style={styles.handle} numberOfLines={1}>
                        {payable ? recipientSubtitle(r) : 'No Prova address — add it to send'}
                      </Text>
                    </View>
                    {payable ? <ChevronRight color={Palette.textMuted} size={20} /> : null}
                  </Card>
                </Pressable>
              );
            })}
          </View>
        )}
        <Button
          label="Add recipient"
          variant="secondary"
          icon={<Plus color={Palette.white} size={18} strokeWidth={2} />}
          onPress={() => router.push('/recipient-new')}
          style={styles.add}
        />
      </Screen>
    );
  }

  // ---- Amount + confirm ----
  return (
    // Money-moving screen: block outright while offline / in maintenance rather than let someone
    // submit a payment we cannot deliver or track.
    <ConnectionGate>
      <Screen scroll>
        {/* Selected recipient */}
        <Card style={styles.recipientCard}>
          <View style={styles.avatar}>
            <Text style={styles.avatarText}>{initials(selected.name)}</Text>
          </View>
          <View style={styles.flex}>
            <Text style={styles.name}>{selected.name}</Text>
            <Text style={styles.handle} numberOfLines={1}>
              {recipientSubtitle(selected)}
            </Text>
          </View>
          {!recipientId ? (
            <Pressable hitSlop={8} onPress={() => setPicked(null)} disabled={busy}>
              <Text style={styles.change}>Change</Text>
            </Pressable>
          ) : null}
        </Card>

        {/* Amount */}
        <View style={styles.amountWrap}>
          <Text style={styles.amountLabel}>Amount ({spendDenom.code})</Text>
          <View style={styles.amountRow}>
            <Text style={styles.assetCode}>{spendDenom.code}</Text>
            <TextInput
              style={styles.amountInput}
              value={amount}
              // Sanitised as typed rather than validated afterwards: strip anything that is not a
              // digit or a single decimal point, and cap the decimals at what the denomination
              // actually has. Someone typing 10.005 is stopped at 10.00 instead of being told off
              // once they finish.
              onChangeText={(text) => setAmount(sanitiseAmount(text, spendDenom.exponent))}
              keyboardType="decimal-pad"
              placeholder="0"
              placeholderTextColor={Palette.textMuted}
              editable={!busy}
              autoFocus
            />
          </View>
          {/*
            `spendable`, deliberately — this screen decides what can leave, and Home shows what is
            owned. The two figures differ while change is unfolded, which is why the word here is
            "available to send" rather than "balance": a person who sees a larger number on Home has
            to be able to tell why without guessing, and the confirming line below completes it.
          */}
          <Text style={styles.balanceHint}>
            Available to send: {formatBalance(money.spendable, money.denom, 'nothing added yet')}
            {amountValid && !canAfford ? '  ·  Insufficient balance' : ''}
          </Text>

          {/*
            Shown only when it bites. Repeating the same figure twice would just be noise; the two
            differ exactly when the balance is split across notes, which is the case worth naming.
          */}
          {usesPool && money.largestNote > 0 && money.largestNote < money.spendable ? (
            <Text style={styles.balanceHint}>
              Most you can send at once: {formatBalance(money.largestNote, money.denom)}
            </Text>
          ) : null}

          {splitNeeded ? (
            <Text style={styles.splitNote}>
              Send {formatBalance(money.largestNote, money.denom)} now, and the remaining{' '}
              {formatBalance(amtMinor - money.largestNote, money.denom)} straight after. Money that
              came in separately has to go out separately.
            </Text>
          ) : null}

          {parsedMinor !== null && !withinTier ? (
            <Text style={styles.splitNote}>
              Your verification level allows up to{' '}
              {formatBalance(
                tierLimit(credential?.kycLevel ?? 0) * minorPerUnit(spendDenom),
                money.denom,
              )}{' '}
              per transfer.
            </Text>
          ) : null}

          {usesPool && money.pending > 0 ? (
            <Text style={styles.balanceHint}>
              {formatBalance(money.pending, money.denom)} still confirming — not yet spendable
            </Text>
          ) : null}
        </View>

        <Button
          label={busy ? message : 'Send privately'}
          onPress={onSend}
          disabled={busy || !amountValid || !canAfford || splitNeeded}
        />

        {busy ? (
          <View style={styles.progressWrap}>
            <View style={styles.progressTrack}>
              <View style={[styles.progressFill, { width: `${Math.round(progress * 100)}%` }]} />
            </View>
            <View style={styles.progressRow}>
              <Loader />
              <Text style={styles.progressText}>{message}</Text>
            </View>
          </View>
        ) : null}

        {error ? <Text style={styles.error}>{error}</Text> : null}
        <Text style={styles.enclave}>
          The amount is proved compliant on this device and never leaves it — only a commitment goes
          on-chain.
        </Text>
        {!isProverAvailable ? (
          <Text style={styles.hint}>
            On-device prover not built into this app yet. Rebuild with `npx expo run:android` to
            enable proving.
          </Text>
        ) : null}

        <ConfirmSendSheet
          visible={confirming}
          amount={formatBalance(amtMinor, money.denom, String(amtMinor / 100))}
          recipientName={selected.name}
          country={selected.country}
          onCancel={() => setConfirming(false)}
          onConfirm={onConfirmed}
        />

        <PinPromptModal
          visible={showPinPrompt}
          title="Approve this transfer"
          subtitle="Enter your PIN to send."
          onSuccess={() => {
            setShowPinPrompt(false);
            runTransfer();
          }}
          onCancel={() => setShowPinPrompt(false)}
        />
      </Screen>
    </ConnectionGate>
  );
}

/**
 * Keep the amount field to a well-formed number as it is typed.
 *
 * Strips anything that is not a digit or a decimal point, keeps only the first point, and caps the
 * decimals at what the denomination has. Correcting the input beats rejecting it afterwards — the
 * person never gets to a state the app then has to complain about.
 */
function sanitiseAmount(text: string, exponent: number): string {
  const cleaned = text.replace(/[^0-9.]/g, '');
  const [whole, ...rest] = cleaned.split('.');
  if (rest.length === 0) return whole;
  if (exponent === 0) return whole;
  return `${whole}.${rest.join('').slice(0, exponent)}`;
}

/** Whether this recipient can actually be paid: the pool address is the only field that moves money. */
function payableRecipient(r: Recipient): boolean {
  return !!(r.poolOwnerPk && r.poolEncPkX && r.poolEncPkY);
}

/**
 * Subtitle under a recipient's name.
 *
 * `handle` is legacy — new recipients are saved without it (see lib/recipients) — so it is only
 * included when an older record actually carries one. Interpolating it unconditionally printed a
 * stray leading separator for every recipient added since.
 */
function recipientSubtitle(r: { handle?: string; country: string }): string {
  return r.handle ? `${r.handle} · ${r.country}` : r.country;
}

const styles = StyleSheet.create({
  subtitle: { ...Typography.body, color: Palette.textSecondary, marginBottom: Spacing.four },
  flex: { flex: 1 },
  gateCard: { gap: Spacing.three, alignItems: 'flex-start', marginBottom: Spacing.four },
  gateTitle: { ...Typography.section, color: Palette.white },
  gateBody: { ...Typography.caption, color: Palette.textSecondary },
  pickList: { gap: Spacing.three, marginBottom: Spacing.four },
  pickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
  },
  pickRowDisabled: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
    opacity: 0.45,
  },
  recipientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
    marginBottom: Spacing.six,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: Radius.full,
    backgroundColor: Palette.bgSelected,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { ...Typography.section, color: Palette.white },
  name: { ...Typography.body, color: Palette.white },
  handle: { ...Typography.micro, color: Palette.textSecondary },
  change: { ...Typography.caption, color: Palette.accent, fontWeight: '600' },
  add: { marginTop: Spacing.two },
  amountWrap: { marginBottom: Spacing.six, gap: Spacing.two },
  amountLabel: { ...Typography.caption, color: Palette.textSecondary },
  amountRow: { flexDirection: 'row', alignItems: 'baseline', gap: Spacing.two },
  assetCode: { ...Typography.title, color: Palette.textSecondary },
  amountInput: {
    ...Typography.displayBalance,
    color: Palette.white,
    flex: 1,
    padding: 0,
  },
  splitNote: {
    ...Typography.caption,
    color: Palette.lilac,
    lineHeight: 20,
    marginTop: Spacing.two,
  },
  balanceHint: { ...Typography.micro, color: Palette.textMuted },
  progressWrap: { marginTop: Spacing.five, gap: Spacing.three },
  progressTrack: {
    height: 6,
    borderRadius: Radius.pill,
    backgroundColor: Palette.bgElevated,
    overflow: 'hidden',
  },
  progressFill: { height: 6, borderRadius: Radius.pill, backgroundColor: Palette.accent },
  progressRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three },
  progressText: { ...Typography.caption, color: Palette.textSecondary },
  error: { ...Typography.caption, color: '#ff6b6b', marginTop: Spacing.four },
  enclave: { ...Typography.micro, color: Palette.textMuted, marginTop: Spacing.four },
  hint: { ...Typography.micro, color: Palette.textMuted, marginTop: Spacing.two },
  successWrap: { alignItems: 'center', gap: Spacing.three, paddingTop: Spacing.seven },
  successBadge: {
    width: 88,
    height: 88,
    borderRadius: Radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.glass,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.glassBorder,
    marginBottom: Spacing.two,
  },
  successTitle: { ...Typography.title, color: Palette.white },
  successBody: { ...Typography.section, color: Palette.accent },
  mono: { ...Typography.micro, color: Palette.textMuted },
  doneBtn: { marginTop: Spacing.six, alignSelf: 'stretch' },
});
